version: '{branch}- 0.0.{build}'
skip_tags: true
configuration:
- Debug
- Release
build:
  project: 3DEngine.sln
  verbosity: normal
before_package:
- ps: Copy-Item C:\projects\3d-motor\Source\$env:CONFIGURATION\3DEngine.exe C:\projects\3d-motor\Game\.
artifacts:
- path: Game
  name: Release
deploy:
- provider: GitHub
  auth_token:
    secure: TTSVGqQ2AwzvL6lROWpObpmbm99AIwvsAd9DVs7C+wttC15wftjIle7G1gjAJGyQ
  artifact: Release
  draft: true
  prerelease: false
  on:
    CONFIGURATION: Release